version: '3.9'

services:
  prod:
    image: foreigncouncil/landing-api:latest
    ports:
      - "5001:5001"
    env_file:
      - .env.prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - landing_api

networks:
  landing_api:
    driver: overlay

#docker stack rm landing_api
#docker stack deploy -c docker-compose.prod.yml landing_api
